name: 'indego_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# configs
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  indego_analytics:
    staging:
      +materialized: view
    core:
      +materialized: table
  
seeds:
  indego_analytics:
    +enabled: true
    stations:
      +column_types:
        station_id: INTEGER
        station_name: STRING
        go_live_date: DATE
        station_status: STRING

vars:
  'dbt_date:time_zone': 'America/New_York'
  bike_types: ['electric', 'standard', 'unknown', '']
  trip_types: ['Round Trip', 'One Way']